user:
  email: "yun@test"
  nickname: "nickname"
  age: 28
  auth: false
  amount: 101

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    data: classpath:init.sql # 시작할때 실행시킬 script

# H2 Settings
h2:
  console:
    enabled: true
    path: /h2-console

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace
